module.exports = {
    name: 'diz',
    aliases: [],
    category: 'Diz',
    utilisation: '{prefix}diz',

    execute(client, message,args) {
       var random = Math.random();
       var choice = Math.floor(random*11);
       const member = args[0];
        if(!member)
        {
            message.channel.send('Choose somebody to diz');
        }
        else{
        
            const target = message.channel.guild.fetch(member.slice(1,member.length))
            message.channel.send({
                embed: {
                    color: 'ORANGE',
                    author: 'Dear' + target.name,
                    footer: { text: '' },
                    fields: [
                        { name: 'Gửi tới', value: args[0], inline: true},
                        { name: 'Ký tên', value: message.author, inline: true },
                    ],
                    timestamp: new Date(),
                    description: dizmau[choice],
                }
            });
        }
    },
};
const dizmau = [
    "Mày nói cái quái gì về tao thế hả, con đĩ con? Tao cho mày biết là tao đã tốt nghiệp đứng đầu lớp trong Mặt trận Dân tộc Giải phóng miền Nam Việt Nam và được ghi nhận đã giết hơn 300 mạng. Tao được đào tạo trong chiến tranh du kích và tao là xạ thủ hàng đầu trong toàn lực lượng vũ trang Bắc Việt. Đối với tao, mày chẳng là gì ngoài một mục tiêu khác. Tao sẽ xóa cái địt mẹ sổ mày với độ chính xác chưa từng có trên Trái Đất này, nhớ cái địt mẹ lời tao đi. Mày nghĩ mày có thể thoát sau khi nói cái cứt đó với tao trên mạng Internet à? Nghĩ lại đi, thằng địt. Trong khi nói chuyện với mày thì tao đang liên lạc mạng lưới bí mật những điệp viên khắp toàn Việt Nam và địa chỉ IP của mày đang bị truy tìm cho nên mày tốt hơn là chuẩn bị cho cuộc bố ráp đi, đồ dòi bọ. Cuộc bố ráp mà sẽ xóa sổ cái thứ nhỏ nhoi là cuộc đời mày đó. Mày tiêu mẹ rồi con. Tao có thể ở bất cứ đâu, bất cứ khi nào, và tao có thể giết mày bằng hơn 700 cách, và đó mới chỉ là dùng tay không thôi. Tao không chỉ được huấn luyện thuần thục về chiến đấu tay không mà còn có thể tiếp cận toàn bộ khí tài của Binh chủng đặc công Việt Nam và tao sẽ sử dụng hết thảy để xóa sổ cái mạng đáng thương của mày khỏi lục địa, đồ cứt trôi. Phải chi mày biết sự trừng phạt khủng khiếp mà lời ý kiến hay ho của mày sẽ sớm đem đến, thì chắc mày đã cẩn thận cái mồm thối của mày. Nhưng mày đã không thể, mày không làm vậy, và giờ mày phải trá giá, thằng khốn ngu ngốc. Tao sẽ ỉa ra sự phẫn nộ lên khắp người mày và mày sẽ chết chìm trong đó. Mày tiêu rồi, thằng nhóc.",
    "Địt con mẹ mày gáy to lên ò ó o ò ó o đm trẻ trâu óc cặc cãi đéo lại cái đầu buồi gì cũng gáy mạnh vcl thế ôi thật là vãi lồn, ôi địt con mẹ mày thằng đầu buồi, ồ nô mày vẫn còn gáy đó à súc vật ? Ái chà địt mẹ thế thì còn chờ gì nữa đi mà không tăng âm lượng đi nào ? Mày phải gáy thật to, thật thật là to mới đủ để t để ý tới mấy thằng lồn mặc cặc đầu buồi như mày đấy. Địt mẹ thất bại của tạo hóa là đây chứ đâu, địt mẹ mày ba má sinh ra thứ loài vật hãm cặc như mày thì ít nhất nếu mày muốn sự quan tâm, thu hút sự chú ý của người khác thì mày phải banh cái mỏ lồn chuyên bú cặc của mày ra, dùng hết khả năng của cái thanh quản trong cổ mà mày chuyên dùng để bú cu ấy để gáy to hơn. Gáy cho muôn đời tốt đẹp, gáy cho muôn vật được vui tươi, gáy cho trái đất được yên bình. Bởi họ biết ở đây có một con chó xạo lồn hãm cặc vẫn cố gân cổ, gằng giọng lên để mà gáy gáy gáy. Cho họ biết rằng mày là một con chó thất bại, và họ vui vì họ sẽ biết mà tránh xa lũ chó dơ bẩn như thế này. Địt con mẹ mày ồ ? Mày nhắc tới bố mẹ tao ư ? Hay lắm đấy con chó, mày đã gáy đủ to để dành được sự chú ý của t rồi đấy. Mày nên mừng sau khi bỏ ra bao bao công sức, gát khang cả giọng và mày đã làm được rồi! Mày đã thành công chứng minh mày chỉ là một con chó súc sinh hạ đẳng chuyên bú cu với cái mồm thối đầy bựa cặc. Kể cả vậy t vẫn cảm thấy tội ba má mày khi sinh ra mày đấy, một thằng điếm thèm cặc mê cu thích sủa, gây ô nhiễm không khí khi tiếp tục gáy và mồm phun đầy bựa cặc và tinh trùng. Địt con mẹ mày nếu mày đã đạt được điều mày muốn là thu hút sự chú ý của tao ? Thì làm ơn mày có thể bớt gáy được không ? Tao đéo ngại phải tiếp những con súc vật hạ đẳng như mày nhưng làm ơn đấy màn gáy của mày đã to đến mức làm phiền những người xung quanh đấy. Họ khác mày là những con người bình thường chứ đéo phải là một con sâu bọ như mày cứ mở mồm ra là gáy và gáy. Ôi chúa ơi, phật tổ ơi những con người đầy quyền năng và mạnh mẽ hãy giúp con trừng trị thứ loài vật khiếm khuyết này. Hãy khóa mõm con thú đáng ghê tởm mà cứ liên tục gáy trước mặt con, hãy trừ họa nó cho một thế giới tươi đẹp hơn, đẹp đẽ hơn. Địt con mẹ mày bớt gáy đi, thứ súc vật gớm ghiếc. Những gì mày gáy ra đéo đủ trình độ, đẳng cấp để tao hiểu đâu hết, thứ chó đẻ",
    "Địt con mẹ mày mày thích mất dạy không thằng lồn? Đụ đỉ mẹ mày con súc vật nông dân móng chân vàng đừng có để tao phải tìm thấy cái mặt lồn nhà mày rồi tao lại bửa nát tử cung khai thông buồng trứng con mẹ mày đấy. Địt con mẹ mày mày thích mất dạy không thằng lồn đụ đỉ con mẹ mày đừng để tao phải tìm ra cái mặt lồn con mẹ mày rồi tao lại tọng vào lồn con đĩ mẹ mày 1000 cái xà beng nung đỏ và 100 tấn xi măng bít lồn con đĩ mẹ mày địt cả lò nhà mày địt từ hoa kỳ sang pháp địt từ pháp sang việt nam địt từ lồn mẹ mày sâu tới tâm trái đất địt cả họ hàng nhà mày mày thích mất dạy không đụ thằng cha con gái mẹ mày thằng lồn thất bại của tạo hóa đụ con đĩ bà già ông cố nội mày thằng cức người để tao gặp mày lần nữa thì đụ con đĩ mẹ mày 1001 cái sextoy đâm vào lồn con mẹ mày. Đụ con đĩ mẹ mày con súc vật lấc cấc mồm lồn còn hôi sữa mà cứ mở họng ra là tỏ vẻ bố thiên nhiên mẹ thiên hạ à con súc vật cái lồn chó má cả lò nhà mày chỉ là vật lót đường thứ lót dái cho tao mà thôi cho nên đừng có để bố mày phải tìm ra cái mặt lồn con đĩ mẹ mày rồi tao lại bít xi măng chằng mạng nhện bện lá khoai cái lồn mẹ mày lại nhé.",
    "Mày nói cái quái gì về tao thế hả, con đĩ con? Tao cho mày biết là tao đã tốt nghiệp đứng đầu lớp trong Mặt trận Dân tộc Giải phóng miền Nam Việt Nam và được ghi nhận đã giết hơn 300 mạng. Tao được đào tạo trong chiến tranh du kích và tao là xạ thủ hàng đầu trong toàn lực lượng vũ trang Bắc Việt. Đối với tao, mày chẳng là gì ngoài một mục tiêu khác. Tao sẽ xóa cái địt mẹ sổ mày với độ chính xác chưa từng có trên Trái Đất này, nhớ cái địt mẹ lời tao đi. Mày nghĩ mày có thể thoát sau khi nói cái cứt đó với tao trên mạng Internet à? Nghĩ lại đi, thằng địt. Trong khi nói chuyện với mày thì tao đang liên lạc mạng lưới bí mật những điệp viên khắp toàn Việt Nam và địa chỉ IP của mày đang bị truy tìm cho nên mày tốt hơn là chuẩn bị cho cuộc bố ráp đi, đồ dòi bọ. Cuộc bố ráp mà sẽ xóa sổ cái thứ nhỏ nhoi là cuộc đời mày đó. Mày tiêu mẹ rồi con. Tao có thể ở bất cứ đâu, bất cứ khi nào, và tao có thể giết mày bằng hơn 700 cách, và đó mới chỉ là dùng tay không thôi. Tao không chỉ được huấn luyện thuần thục về chiến đấu tay không mà còn có thể tiếp cận toàn bộ khí tài của Binh chủng đặc công Việt Nam và tao sẽ sử dụng hết thảy để xóa sổ cái mạng đáng thương của mày khỏi lục địa, đồ cứt trôi. Phải chi mày biết sự trừng phạt khủng khiếp mà lời ý kiến hay ho của mày sẽ sớm đem đến, thì chắc mày đã cẩn thận cái mồm thối của mày. Nhưng mày đã không thể, mày không làm vậy, và giờ mày phải trá giá, thằng khốn ngu ngốc. Tao sẽ ỉa ra sự phẫn nộ lên khắp người mày và mày sẽ chết chìm trong đó. Mày tiêu rồi, thằng nhóc.",
    "Địt con mẹ mày gáy to lên ò ó o ò ó o đm trẻ trâu óc cặc cãi đéo lại cái đầu buồi gì cũng gáy mạnh vcl thế ôi thật là vãi lồn, ôi địt con mẹ mày thằng đầu buồi, ồ nô mày vẫn còn gáy đó à súc vật ? Ái chà địt mẹ thế thì còn chờ gì nữa đi mà không tăng âm lượng đi nào ? Mày phải gáy thật to, thật thật là to mới đủ để t để ý tới mấy thằng lồn mặc cặc đầu buồi như mày đấy. Địt mẹ thất bại của tạo hóa là đây chứ đâu, địt mẹ mày ba má sinh ra thứ loài vật hãm cặc như mày thì ít nhất nếu mày muốn sự quan tâm, thu hút sự chú ý của người khác thì mày phải banh cái mỏ lồn chuyên bú cặc của mày ra, dùng hết khả năng của cái thanh quản trong cổ mà mày chuyên dùng để bú cu ấy để gáy to hơn. Gáy cho muôn đời tốt đẹp, gáy cho muôn vật được vui tươi, gáy cho trái đất được yên bình. Bởi họ biết ở đây có một con chó xạo lồn hãm cặc vẫn cố gân cổ, gằng giọng lên để mà gáy gáy gáy. Cho họ biết rằng mày là một con chó thất bại, và họ vui vì họ sẽ biết mà tránh xa lũ chó dơ bẩn như thế này. Địt con mẹ mày ồ ? Mày nhắc tới bố mẹ tao ư ? Hay lắm đấy con chó, mày đã gáy đủ to để dành được sự chú ý của t rồi đấy. Mày nên mừng sau khi bỏ ra bao bao công sức, gát khang cả giọng và mày đã làm được rồi! Mày đã thành công chứng minh mày chỉ là một con chó súc sinh hạ đẳng chuyên bú cu với cái mồm thối đầy bựa cặc. Kể cả vậy t vẫn cảm thấy tội ba má mày khi sinh ra mày đấy, một thằng điếm thèm cặc mê cu thích sủa, gây ô nhiễm không khí khi tiếp tục gáy và mồm phun đầy bựa cặc và tinh trùng. Địt con mẹ mày nếu mày đã đạt được điều mày muốn là thu hút sự chú ý của tao ? Thì làm ơn mày có thể bớt gáy được không ? Tao đéo ngại phải tiếp những con súc vật hạ đẳng như mày nhưng làm ơn đấy màn gáy của mày đã to đến mức làm phiền những người xung quanh đấy. Họ khác mày là những con người bình thường chứ đéo phải là một con sâu bọ như mày cứ mở mồm ra là gáy và gáy. Ôi chúa ơi, phật tổ ơi những con người đầy quyền năng và mạnh mẽ hãy giúp con trừng trị thứ loài vật khiếm khuyết này. Hãy khóa mõm con thú đáng ghê tởm mà cứ liên tục gáy trước mặt con, hãy trừ họa nó cho một thế giới tươi đẹp hơn, đẹp đẽ hơn. Địt con mẹ mày bớt gáy đi, thứ súc vật gớm ghiếc. Những gì mày gáy ra đéo đủ trình độ, đẳng cấp để tao hiểu đâu hết, thứ chó đẻ",
    "Địt con mẹ mày mày thích mất dạy không thằng lồn? Đụ đỉ mẹ mày con súc vật nông dân móng chân vàng đừng có để tao phải tìm thấy cái mặt lồn nhà mày rồi tao lại bửa nát tử cung khai thông buồng trứng con mẹ mày đấy. Địt con mẹ mày mày thích mất dạy không thằng lồn đụ đỉ con mẹ mày đừng để tao phải tìm ra cái mặt lồn con mẹ mày rồi tao lại tọng vào lồn con đĩ mẹ mày 1000 cái xà beng nung đỏ và 100 tấn xi măng bít lồn con đĩ mẹ mày địt cả lò nhà mày địt từ hoa kỳ sang pháp địt từ pháp sang việt nam địt từ lồn mẹ mày sâu tới tâm trái đất địt cả họ hàng nhà mày mày thích mất dạy không đụ thằng cha con gái mẹ mày thằng lồn thất bại của tạo hóa đụ con đĩ bà già ông cố nội mày thằng cức người để tao gặp mày lần nữa thì đụ con đĩ mẹ mày 1001 cái sextoy đâm vào lồn con mẹ mày. Đụ con đĩ mẹ mày con súc vật lấc cấc mồm lồn còn hôi sữa mà cứ mở họng ra là tỏ vẻ bố thiên nhiên mẹ thiên hạ à con súc vật cái lồn chó má cả lò nhà mày chỉ là vật lót đường thứ lót dái cho tao mà thôi cho nên đừng có để bố mày phải tìm ra cái mặt lồn con đĩ mẹ mày rồi tao lại bít xi măng chằng mạng nhện bện lá khoai cái lồn mẹ mày lại nhé.",
    "Mày nói cái quái gì về tao thế hả, con đĩ con? Tao cho mày biết là tao đã tốt nghiệp đứng đầu lớp trong Mặt trận Dân tộc Giải phóng miền Nam Việt Nam và được ghi nhận đã giết hơn 300 mạng. Tao được đào tạo trong chiến tranh du kích và tao là xạ thủ hàng đầu trong toàn lực lượng vũ trang Bắc Việt. Đối với tao, mày chẳng là gì ngoài một mục tiêu khác. Tao sẽ xóa cái địt mẹ sổ mày với độ chính xác chưa từng có trên Trái Đất này, nhớ cái địt mẹ lời tao đi. Mày nghĩ mày có thể thoát sau khi nói cái cứt đó với tao trên mạng Internet à? Nghĩ lại đi, thằng địt. Trong khi nói chuyện với mày thì tao đang liên lạc mạng lưới bí mật những điệp viên khắp toàn Việt Nam và địa chỉ IP của mày đang bị truy tìm cho nên mày tốt hơn là chuẩn bị cho cuộc bố ráp đi, đồ dòi bọ. Cuộc bố ráp mà sẽ xóa sổ cái thứ nhỏ nhoi là cuộc đời mày đó. Mày tiêu mẹ rồi con. Tao có thể ở bất cứ đâu, bất cứ khi nào, và tao có thể giết mày bằng hơn 700 cách, và đó mới chỉ là dùng tay không thôi. Tao không chỉ được huấn luyện thuần thục về chiến đấu tay không mà còn có thể tiếp cận toàn bộ khí tài của Binh chủng đặc công Việt Nam và tao sẽ sử dụng hết thảy để xóa sổ cái mạng đáng thương của mày khỏi lục địa, đồ cứt trôi. Phải chi mày biết sự trừng phạt khủng khiếp mà lời ý kiến hay ho của mày sẽ sớm đem đến, thì chắc mày đã cẩn thận cái mồm thối của mày. Nhưng mày đã không thể, mày không làm vậy, và giờ mày phải trá giá, thằng khốn ngu ngốc. Tao sẽ ỉa ra sự phẫn nộ lên khắp người mày và mày sẽ chết chìm trong đó. Mày tiêu rồi, thằng nhóc.",
    "Địt con mẹ mày gáy to lên ò ó o ò ó o đm trẻ trâu óc cặc cãi đéo lại cái đầu buồi gì cũng gáy mạnh vcl thế ôi thật là vãi lồn, ôi địt con mẹ mày thằng đầu buồi, ồ nô mày vẫn còn gáy đó à súc vật ? Ái chà địt mẹ thế thì còn chờ gì nữa đi mà không tăng âm lượng đi nào ? Mày phải gáy thật to, thật thật là to mới đủ để t để ý tới mấy thằng lồn mặc cặc đầu buồi như mày đấy. Địt mẹ thất bại của tạo hóa là đây chứ đâu, địt mẹ mày ba má sinh ra thứ loài vật hãm cặc như mày thì ít nhất nếu mày muốn sự quan tâm, thu hút sự chú ý của người khác thì mày phải banh cái mỏ lồn chuyên bú cặc của mày ra, dùng hết khả năng của cái thanh quản trong cổ mà mày chuyên dùng để bú cu ấy để gáy to hơn. Gáy cho muôn đời tốt đẹp, gáy cho muôn vật được vui tươi, gáy cho trái đất được yên bình. Bởi họ biết ở đây có một con chó xạo lồn hãm cặc vẫn cố gân cổ, gằng giọng lên để mà gáy gáy gáy. Cho họ biết rằng mày là một con chó thất bại, và họ vui vì họ sẽ biết mà tránh xa lũ chó dơ bẩn như thế này. Địt con mẹ mày ồ ? Mày nhắc tới bố mẹ tao ư ? Hay lắm đấy con chó, mày đã gáy đủ to để dành được sự chú ý của t rồi đấy. Mày nên mừng sau khi bỏ ra bao bao công sức, gát khang cả giọng và mày đã làm được rồi! Mày đã thành công chứng minh mày chỉ là một con chó súc sinh hạ đẳng chuyên bú cu với cái mồm thối đầy bựa cặc. Kể cả vậy t vẫn cảm thấy tội ba má mày khi sinh ra mày đấy, một thằng điếm thèm cặc mê cu thích sủa, gây ô nhiễm không khí khi tiếp tục gáy và mồm phun đầy bựa cặc và tinh trùng. Địt con mẹ mày nếu mày đã đạt được điều mày muốn là thu hút sự chú ý của tao ? Thì làm ơn mày có thể bớt gáy được không ? Tao đéo ngại phải tiếp những con súc vật hạ đẳng như mày nhưng làm ơn đấy màn gáy của mày đã to đến mức làm phiền những người xung quanh đấy. Họ khác mày là những con người bình thường chứ đéo phải là một con sâu bọ như mày cứ mở mồm ra là gáy và gáy. Ôi chúa ơi, phật tổ ơi những con người đầy quyền năng và mạnh mẽ hãy giúp con trừng trị thứ loài vật khiếm khuyết này. Hãy khóa mõm con thú đáng ghê tởm mà cứ liên tục gáy trước mặt con, hãy trừ họa nó cho một thế giới tươi đẹp hơn, đẹp đẽ hơn. Địt con mẹ mày bớt gáy đi, thứ súc vật gớm ghiếc. Những gì mày gáy ra đéo đủ trình độ, đẳng cấp để tao hiểu đâu hết, thứ chó đẻ",
    "Địt con mẹ mày mày thích mất dạy không thằng lồn? Đụ đỉ mẹ mày con súc vật nông dân móng chân vàng đừng có để tao phải tìm thấy cái mặt lồn nhà mày rồi tao lại bửa nát tử cung khai thông buồng trứng con mẹ mày đấy. Địt con mẹ mày mày thích mất dạy không thằng lồn đụ đỉ con mẹ mày đừng để tao phải tìm ra cái mặt lồn con mẹ mày rồi tao lại tọng vào lồn con đĩ mẹ mày 1000 cái xà beng nung đỏ và 100 tấn xi măng bít lồn con đĩ mẹ mày địt cả lò nhà mày địt từ hoa kỳ sang pháp địt từ pháp sang việt nam địt từ lồn mẹ mày sâu tới tâm trái đất địt cả họ hàng nhà mày mày thích mất dạy không đụ thằng cha con gái mẹ mày thằng lồn thất bại của tạo hóa đụ con đĩ bà già ông cố nội mày thằng cức người để tao gặp mày lần nữa thì đụ con đĩ mẹ mày 1001 cái sextoy đâm vào lồn con mẹ mày. Đụ con đĩ mẹ mày con súc vật lấc cấc mồm lồn còn hôi sữa mà cứ mở họng ra là tỏ vẻ bố thiên nhiên mẹ thiên hạ à con súc vật cái lồn chó má cả lò nhà mày chỉ là vật lót đường thứ lót dái cho tao mà thôi cho nên đừng có để bố mày phải tìm ra cái mặt lồn con đĩ mẹ mày rồi tao lại bít xi măng chằng mạng nhện bện lá khoai cái lồn mẹ mày lại nhé.",
    "Mày nói cái quái gì về tao thế hả, con đĩ con? Tao cho mày biết là tao đã tốt nghiệp đứng đầu lớp trong Mặt trận Dân tộc Giải phóng miền Nam Việt Nam và được ghi nhận đã giết hơn 300 mạng. Tao được đào tạo trong chiến tranh du kích và tao là xạ thủ hàng đầu trong toàn lực lượng vũ trang Bắc Việt. Đối với tao, mày chẳng là gì ngoài một mục tiêu khác. Tao sẽ xóa cái địt mẹ sổ mày với độ chính xác chưa từng có trên Trái Đất này, nhớ cái địt mẹ lời tao đi. Mày nghĩ mày có thể thoát sau khi nói cái cứt đó với tao trên mạng Internet à? Nghĩ lại đi, thằng địt. Trong khi nói chuyện với mày thì tao đang liên lạc mạng lưới bí mật những điệp viên khắp toàn Việt Nam và địa chỉ IP của mày đang bị truy tìm cho nên mày tốt hơn là chuẩn bị cho cuộc bố ráp đi, đồ dòi bọ. Cuộc bố ráp mà sẽ xóa sổ cái thứ nhỏ nhoi là cuộc đời mày đó. Mày tiêu mẹ rồi con. Tao có thể ở bất cứ đâu, bất cứ khi nào, và tao có thể giết mày bằng hơn 700 cách, và đó mới chỉ là dùng tay không thôi. Tao không chỉ được huấn luyện thuần thục về chiến đấu tay không mà còn có thể tiếp cận toàn bộ khí tài của Binh chủng đặc công Việt Nam và tao sẽ sử dụng hết thảy để xóa sổ cái mạng đáng thương của mày khỏi lục địa, đồ cứt trôi. Phải chi mày biết sự trừng phạt khủng khiếp mà lời ý kiến hay ho của mày sẽ sớm đem đến, thì chắc mày đã cẩn thận cái mồm thối của mày. Nhưng mày đã không thể, mày không làm vậy, và giờ mày phải trá giá, thằng khốn ngu ngốc. Tao sẽ ỉa ra sự phẫn nộ lên khắp người mày và mày sẽ chết chìm trong đó. Mày tiêu rồi, thằng nhóc.",
    "Địt con mẹ mày gáy to lên ò ó o ò ó o đm trẻ trâu óc cặc cãi đéo lại cái đầu buồi gì cũng gáy mạnh vcl thế ôi thật là vãi lồn, ôi địt con mẹ mày thằng đầu buồi, ồ nô mày vẫn còn gáy đó à súc vật ? Ái chà địt mẹ thế thì còn chờ gì nữa đi mà không tăng âm lượng đi nào ? Mày phải gáy thật to, thật thật là to mới đủ để t để ý tới mấy thằng lồn mặc cặc đầu buồi như mày đấy. Địt mẹ thất bại của tạo hóa là đây chứ đâu, địt mẹ mày ba má sinh ra thứ loài vật hãm cặc như mày thì ít nhất nếu mày muốn sự quan tâm, thu hút sự chú ý của người khác thì mày phải banh cái mỏ lồn chuyên bú cặc của mày ra, dùng hết khả năng của cái thanh quản trong cổ mà mày chuyên dùng để bú cu ấy để gáy to hơn. Gáy cho muôn đời tốt đẹp, gáy cho muôn vật được vui tươi, gáy cho trái đất được yên bình. Bởi họ biết ở đây có một con chó xạo lồn hãm cặc vẫn cố gân cổ, gằng giọng lên để mà gáy gáy gáy. Cho họ biết rằng mày là một con chó thất bại, và họ vui vì họ sẽ biết mà tránh xa lũ chó dơ bẩn như thế này. Địt con mẹ mày ồ ? Mày nhắc tới bố mẹ tao ư ? Hay lắm đấy con chó, mày đã gáy đủ to để dành được sự chú ý của t rồi đấy. Mày nên mừng sau khi bỏ ra bao bao công sức, gát khang cả giọng và mày đã làm được rồi! Mày đã thành công chứng minh mày chỉ là một con chó súc sinh hạ đẳng chuyên bú cu với cái mồm thối đầy bựa cặc. Kể cả vậy t vẫn cảm thấy tội ba má mày khi sinh ra mày đấy, một thằng điếm thèm cặc mê cu thích sủa, gây ô nhiễm không khí khi tiếp tục gáy và mồm phun đầy bựa cặc và tinh trùng. Địt con mẹ mày nếu mày đã đạt được điều mày muốn là thu hút sự chú ý của tao ? Thì làm ơn mày có thể bớt gáy được không ? Tao đéo ngại phải tiếp những con súc vật hạ đẳng như mày nhưng làm ơn đấy màn gáy của mày đã to đến mức làm phiền những người xung quanh đấy. Họ khác mày là những con người bình thường chứ đéo phải là một con sâu bọ như mày cứ mở mồm ra là gáy và gáy. Ôi chúa ơi, phật tổ ơi những con người đầy quyền năng và mạnh mẽ hãy giúp con trừng trị thứ loài vật khiếm khuyết này. Hãy khóa mõm con thú đáng ghê tởm mà cứ liên tục gáy trước mặt con, hãy trừ họa nó cho một thế giới tươi đẹp hơn, đẹp đẽ hơn. Địt con mẹ mày bớt gáy đi, thứ súc vật gớm ghiếc. Những gì mày gáy ra đéo đủ trình độ, đẳng cấp để tao hiểu đâu hết, thứ chó đẻ",
    "Địt con mẹ mày mày thích mất dạy không thằng lồn? Đụ đỉ mẹ mày con súc vật nông dân móng chân vàng đừng có để tao phải tìm thấy cái mặt lồn nhà mày rồi tao lại bửa nát tử cung khai thông buồng trứng con mẹ mày đấy. Địt con mẹ mày mày thích mất dạy không thằng lồn đụ đỉ con mẹ mày đừng để tao phải tìm ra cái mặt lồn con mẹ mày rồi tao lại tọng vào lồn con đĩ mẹ mày 1000 cái xà beng nung đỏ và 100 tấn xi măng bít lồn con đĩ mẹ mày địt cả lò nhà mày địt từ hoa kỳ sang pháp địt từ pháp sang việt nam địt từ lồn mẹ mày sâu tới tâm trái đất địt cả họ hàng nhà mày mày thích mất dạy không đụ thằng cha con gái mẹ mày thằng lồn thất bại của tạo hóa đụ con đĩ bà già ông cố nội mày thằng cức người để tao gặp mày lần nữa thì đụ con đĩ mẹ mày 1001 cái sextoy đâm vào lồn con mẹ mày. Đụ con đĩ mẹ mày con súc vật lấc cấc mồm lồn còn hôi sữa mà cứ mở họng ra là tỏ vẻ bố thiên nhiên mẹ thiên hạ à con súc vật cái lồn chó má cả lò nhà mày chỉ là vật lót đường thứ lót dái cho tao mà thôi cho nên đừng có để bố mày phải tìm ra cái mặt lồn con đĩ mẹ mày rồi tao lại bít xi măng chằng mạng nhện bện lá khoai cái lồn mẹ mày lại nhé.",
    
]