module.exports = {
    name: 'vanmau',
    aliases: [],
    category: 'Vanmau',
    utilisation: '{prefix}vanmau',

    execute(client, message) {
        var random = Math.random();
        var choice = Math.floor(random*11);
        message.channel.send({
            embed: {
                color: '#f54284',
                title: 'Văn mẫu số ' + choice,
                footer: { text: '' },
                fields: [
                    
                ],
                timestamp: new Date(),
                description: vanmau[choice],
            }
        })
    },
};
const vanmau = [
    "CÂM CÁI MỒM CHÓ MÀY LẠI THẰNG LỒN SÚC VẬT NÀY. BỐ MÀY ĐÃ NÓI MÀY BAO NHIÊU LẦN RỒI RỒI LÀ ĐỊT CÁI LỒN MẸ MÀY ĐỪNG BAO GIỜ LẤY WAIFU NGƯỜI KHÁC RA LÀM TRÒ ĐÙA RỒI HẢ HÊ NHƯ KIỂU NHƯ MÌNH HÀI HƯỚC LẮM ẤY ĐỊT CON MẸ MÀY ĐÉO CÓ LIÊM SỈ THÌ THÔI TAO ĐÉO NÓI NHƯNG CON NGƯỜI CHỨ CÓ PHẢI CON CẶC ĐÂU MÀ ĐỂ TAO PHẢI NHẮC LẠI NHIỀU LẦN ĐẾN NHƯ VẬY. TAO ĐÉO PHẢI DẠNG THÍCH NỔI NÓNG CŨNG CHẢ PHẢI LOẠI VÔ HỌC NHƯNG TAO CÓ THỂ NÓI THẲNG MÀY ĐÉO KHÁC GÌ MỘT THẰNG RÁC RƯỞI, RIÊNG Ở ĐIỂM MÀY ĐEM VỢ NGƯỜI KHÁC RA LÀM TRÒ ĐÙA THÌ ĐÃ BIẾT ĐƯỢC MÀY KHÔNG THUA GÌ MỘT THẰNG CHÓ ĐẺ RỒI. MÀY CÓ THỂ CÂM CON MẸ NÓ MIỆNG VÀO VÀ CÚT RA KHỎI CUỘC ĐỜI TAO. VÀ ĐỪNG ĐỂ TAO PHẢI NHÌN THẤY CÁI BẢN MẶT CHÓ ĐẺ CỦA MÀY MỘT LẦN NỮA ĐỤ MÁ THẰNG SÚC VẬT THÍCH LÔI NGƯỜI KHÁC RA LÀM TRÒ ĐÙA. MÀY XÚC PHẠM REM THÌ CHÍNH LÀ MÀY ĐỤNG ĐẾN TAO. MỘT HAI LẦN THÌ TAO ĐÉO NÓI. ĐÂY ĐÃ LÀ QUÁ NHIỀU LẦN RỒI. TAO ĐÉO THỂ NÀO CHỊU ĐỰNG ĐƯỢC NỮA. CÚT CON MẸ MÀY RA KHỎI CUỘC ĐỜI TAO NGAY VÀ LUÔN THẰNG LỒN BÒ CÁI BÚ DÁI CON BÒ ĐỰC.",
    "OMAE CỐ TÌNH CHỬI WATASHI DESU KA? TỪ TANJOUBI ĐẾN KONNICHI, WATASHI ĐÃ ĐƯỢC OSOWARU NÊN HITO, WATASHI KHÔNG BAO GIỜ XÚC PHẠM DARE CẢ, OMAE LÀM VẬY LÀ TONDEMONAI DAYO.TUY WATASHI CÓ HƠI WIBU SUKOSHI, DEMO WATASHI LUÔN ĐẶT NIỀM TIN VÀO ANIME VÀ SỐNG ĐÚNG KIỂU TRONG ANIME, ANIME LÀ 1 THỨ GÌ ĐÓ CAO CẢ HƠN CẢ GENJITSU, WATASHI ĐÃ LÀM THEO VÀ HỌC TẬP THEO TỪ ANIME, WATASHI ĐÃ ĂN UỐNG NGỦ NGHĨ THEO ĐÚNG GIỜ CỦA ANIME MÀ KHÔNG LÀM PHIỀN DARE, ĐÔI LÚC WATASHI CÓ CHỬI VÀO OMAE NO KAO NHƯ INU, DEMO SAU ĐÓ BLOCK NÓ THÌ WATASHI KHÔNG LÀM VIỆC ĐÓ NỮA, MAIKAI MAIKAI WATASHI MUỐN CHỬI DARE WATASHI ĐỀU COI ANIME VÀ GHI NHỚ RẰNG KHÔNG NÊN CHỬI NGƯỜI ĐÓ NỮA !! WATASHI ĐÃ CỐ GẮNG HIỀN HẬU ĐẾN MỨC MUỐN THÀNH HOTOKE RỒI MÀ KARERA VẪN KHÔNG ĐỂ WATASHI YÊN LÀ SAO, YABAI WATASHI KHÔNG NÊN GHI RA NHỮNG TỪ NÀY DEMO THẰNG YAROU SÚC VẬT NÓ LÔI WATASHI NO NA RA ĐỂ CHỬI, THỨ AHO SHUKU SEIBUTSUGAKU KAGAKU BUNGAKU, VẬY LÀ ĐỦ, ĐỪNG ĐỂ WATASHI TRIGGERED VÀ WATASHI DẠY OMAE CÁCH ĐỂ HỌC TẬP VÀ LÀM THEO TẤM GƯƠNG CỦA ANIME NỮA!, THẾ NHÉ INU WA KUSO O TABERU",
    "Nói thật, ❗️ các bạn làm ơn 🙏 đừng lôi chuyện 'Hận❌❌ đàn bà 👩' ra làm trò đùa🙅‍♀️. Nói 1️⃣-2️⃣ câu người ta còn thấy giải trí😂, chứ lâu dài😵 nó thành câu đùa nhảm 🤪không❌ tả được. Mưa🌧 to quá, hận🚷 đàn bà. Mạng📶 yếu quá, 🚷hận đàn bà. Nghỉ dịch🏠 không được đi chơi, 🚷hận đàn bà❓❓❓ Các bạn 🤦‍♀️ không thấy nó nhảm vl à😱. Nếu không ❌nghĩ 🤔 ra được cap hay đăng ảnh 🤳thì có thể đăng ảnh 0️⃣ cap, đừng❌❌ lôi đàn bà 🧍‍♀️ ra làm trò đùa của các bạn rồi thù🤢 với chả hận🤮? Mẹ bạn👩 có phải đàn bà không 🤦‍♀️? Bà 👩🏼‍🦳 bạn có phải đàn bà 🧘‍♀️ không? Cô, bác 👵👵của bạn cũng có phải đàn bà không? Không có đàn bà🧍‍♀️ thì có sự tồn tại của bạn👼 ngày hôm này không❓ Làm ơn 🙏đừng lôi mấy việc linh tinh ra để hẬn ❌❌ĐàN bÀ 🚷nữa, mình thấy chướng mắt 👀 lắm rồi. Còn nếu ❗️bạn có ý định đăng 📝cap như vậy thì hãy tự động ⚙️hủy kết bạn❌ hoặc block 🚫🚫mình luôn đi❗️❗️❗️, mình 0️⃣muốn thấy thêm 1️⃣ lần nào nữa đâu😩😩",
    "Nói thẳng 1 câu nha :) bạn bè như cặc đm bạn sống chó vừa phải thôi :) bạn bè quen nhau mà toàn đi đá đểu nhau ko :) sống chó vừa thôi bạn :) trên fb thì mồm to ra đường t thấy t xiên chết cụ m nha m :) đừng có cậy anh hùng bàn phím. :) bố đời thiên hạ. Ngứa cả đít :) Lời cuối cùng :) tao với mày đéo là bạn đéo gì hết , đéo có ai muốn kết thân với loại ăn cháo đá bác :) chơi k đc rồi đi bêu rếu tao 🙂? Như lồn :) muốn gì thì hẹn nhau xiên nhau? Đừng sủa lồn trên mạng ảo :) hèn vãi lồn :) Giả tạo là bản chất thật của mày sao :) ok fine :) loại như mày thì cút mẹ đi :) tao đéo cần loại bạn như mày :) cứ tưởng mình ngon :) mày chỉ là con bitch thôi :) loại như mày phải rì mu rồi ban phước :) lời cuối :) Dí lồn tao care :) mặt lồn như mày vứt cho chó cũng đéo con nào chơi nổi :) tao đã im lặng vì đéo muốn làm lớn chuyện rồi :) nhưng m cứ xồn xồn lên :) đầu óc có máu lồn à :) hành xử như con cặc? Bú cặc thiên hạ kiếm tiền mà nghĩ mình hay :) :) thân !!",
    "tHế nÀo ‼️⁉️ lÀ hJp hOp 😤😤😖😖 dÂy cHuYềN vÀnG🏅🏅🏆🏆🎖 lÈ lƯỡI lẤy Le 😝😝 mỚi GọI 🗣🗣 lÀ hJp hOp🤡🤡 tAy 🤲🤚🖕 cHâN 🦶🦵 mIệNg👄👅 xỎ nHiỀu pÁnK xE 🍩🍩⭕️⭕️ mỚi gỌi🗣🗣 lÀ hJp hOp 😎😎🤪🤪 mẮt hÍp 👁👀 mỒm hÓp👄💋👅 LuÔn nGhĨ 🤨🧐mÌnH gUcCi 😎😎🤡🤡 cHỉ kHiẾn m nGu 🤪🤪 đI 🚶‍♂️🚶‍♂️bỞi vÌ hJp hOp 🙏😤 đẾn tỪ tRoNg tƯ dUy 🧠🧠 mÃi mÃi 🙊🙊 ĐứNg đẰnG sAu 🚶‍♂️👉🚶‍♂️cẮn 🥶😬 cÀnG 🦀🦞 lÉn tHì cÀnG🦀🦞 đAu 😖😖 cẢ đỜi m ChỈ nGưỚc 🤥🤥😲😲 tHeO t m mUốN lEo cAo 🧗‍♀️🧗‍♀️ nHưNg kO tHể ❌💢🚫⭕️ bẰnG nHaU kO ⭕fLeX kO ⭕fLeX nHư dIễN vIêN xIếC 🤹‍♂️🤹 dA kHôNg cẦn tHa tHu 🦁🦅🕷 nHạC 🎵🎶 vẪn lUôN LiT 🔥🔥 kO cẦn lẤc cẤc 👌🖕🤞 nHư đI 🚶‍♂️🚶‍♂️ vÀo tAbOo cHó 🐕🐕 cẮn cÀn 🥶😬 tHưỜnG lÀ tHíCh nHe rĂng 😁😁 cHấT rẮn vÀnG 🏆🏅🎖 đÒi gẮn xÍcH xE🚗🚗 tĂnG ⬆️⬆️ nÊn hỌc nÓi 🗣🗣 tRưỚc kHi m hỌc ăN 😮🐶 bỎ qUêN cÁcH fAt Âm kHi tỤi m hỌc vĂn 💯💯 brrrzzz.. 🤡🤡🤡   ",
    "LỚN RỒI SỐNG KIẾP NGƯỜI ĐI RẢNH LỒN QUÁ ĐI SỐNG KIỂU THÚ VẬT CHI VẬY BẠN ƠI Đéo hiểu sao nay bữa được mùa hay gì mà bị nứng lồn vậy con chó đẻ ? Loại m rác rưởi mà cứ nghĩ mình là tâm của xã hội , hôm nay lại còn bày đặt dãy lên toxic 😏 Nói cho mày biết , rác thì dù có cố làm tâm điểm như thế nào thì cũng chỉ là rác thôi , việc của mình lo còn chưa xong bày đặt chỉ dạy nhận xét người khác hahaha . Bình thường thì bố mày sẽ nhịn mày vì đôi ba lời nói của mày đéo có giá trị với bố mày nhưng hôm nay mày động đến anh em bạn bè của tao , sỉ nhục những người mà t xem trọng , nên tao phải chửi vào cái bản mặt chó mày , sống thì phải biết nhìn trước nhìn sau , oke ? Thân gửi bạn nào đó tối nay giãy đành đạch toxic với anh em tao 😌 ",
    "Ôi bạn ơi! Bạn sức đề kháng kém là do bạn không chơi đồ đấy bạn ạ, nếu bạn chơi đồ vào thì là đề kháng nó khỏe nó không bao giờ bị ốm đâu bạn ạ, chơi đồ là thuốc bổ mà bạn! Bạn phải nên nhớ nhá, cái viên thuốc bình thường, cái viết thuốc ACID B1 bạn mua có 2 nghìn đc mấy viên đúng k ? Hoặc là 10 nghìn 1 viên, 10 nghìn 1 viên là ACID B1 đấy , đúng không? Thế đây những viên thuốc như viên thuốc kẹo, viên thuốc kim cương, viên thuốc vương liệm này, viên thuốc các kiểu lày thì bạn mua cái đấy vào 500 nghìn 1 viên cơ mà! Chơi cái đấy vào đề kháng nó phải cao hơn chứ bạn! Chơi cái đấy vào nhiều đề kháng mà! Bạn không chơi vào đề kháng bạn kém là phải đấy bạn ạ !",
    "Không vui chút nào, tôi đã không cười. Trò đùa của bạn thật tệ, tôi sẽ thích trò đùa này nếu nó được xoá khỏi đầu tôi và bạn vui lòng từ bỏ nói lại cho tôi trò đùa đấy. Nói thật, đây là một nỗ lực kinh khủng khi cố gắng để mang một nụ cười ra khỏi tôi. Không phải cười, không phải hehe, thậm chí không phải là một sự bùng nổ tinh tế từ thực quản của tôi. Khoa học có nói trước khi bạn cười não của bạn chuẩn bị cơ mặt nhưng tôi thậm chí không cảm thấy một chuyển động nào dù là nhỏ nhất. 0/10 trò đùa này thật tệ, tôi không thể tin là có người lại đủ pháp lý để cho phép bạn được quyền sáng tạo. Lượng sức mạnh não bộ mà bạn đã đưa vào trò đùa đó có thể tạo năng lượng cho mọi ngôi nhà trên Trái Đất. Hãy có một nhân cách và học cách tạo ra trò đùa, đọc một cuốn sách đi. Tôi không nói điều này để trở nên buồn cười, tôi thực sự có ý đó về cách mà đây chỉ là sự bi hài trong hài kịch. Bạn đã giết chết sự hài hước và mọi hành động hài kịch trên hành tinh. Tôi rất thất vọng vì xã hội đã thất bại trong việc có thể dạy bạn cách hài hước. Thật lòng mà nói nếu tôi đặt tất cả sức mạnh và thời gian để cố gắng và làm cho trò đùa của bạn buồn cười, nó sẽ yêu cầu Einstein phải xây dựng một thiết bị để tôi có thể kết nối với năng lượng của một tỷ ngôi sao để làm điều đó, và thứ duy nhất mà trò đùa đó nhận được từ mọi người là một sự khinh bỉ tinh tế. Bạn thật may mắn vì tôi vẫn còn chút cảm thông cho bạn sau khi kể trò đùa đó nếu không tôi sẽ nhận hết mọi tội ác chiến tranh từng được ghi lại trong sử sách chỉ để ngăn cản bạn cố gắng mang đến bất kỳ sự hài hước nào nữa. Chúng ta nên đặt trò đùa đó vào sách giáo khoa để các thế hệ tương lai có thể cảnh giác khỏi việc trở thành một thất bại tuyệt đối trong hài kịch. Tôi thất vọng, tổn thương và bị xúc phạm hoàn toàn khi thời gian quý báu của tôi đã bị lãng phí chỉ để não tôi có thể hiểu trò đùa đó. Trong khoảng thời gian đó tôi đã lên kế hoạch giúp đỡ những đứa trẻ mồ côi, nhưng vì điều đó bạn đã làm tôi đã phải giải thích với một cách ít tục tĩu nhất về nỗ lực khủng khiếp của bạn trong hài kịch. Bây giờ những đứa trẻ đang đau khổ khi không có bữa ăn và không có ai để đổ lỗi ngoài bạn. Tôi hy vọng bạn hạnh phúc với những gì bạn đã làm và tôi thực sự hy vọng bạn có thể bước tiếp và học hỏi từ nỗ lực đáng thương này.",
    "Xin chào bạn, tôi là nhà tuyển dụng của tập đoàn giải trí Rạp xiếc Trung Ương Group. Trong quá trình tìm kiếm và đào tạo những người hài hước của chúng tôi (đi săn chất xám và nhân tài) tôi nhận thấy bạn là người có khiếu hài hước, tập đoàn chúng tôi thật sự cần một chú hề đúng nghĩa, tôi đã thấy bạn vừa mở mồm là mọi người đã cười ầm lên, không cần phải biểu diễn. Đặc biệt đối với chúng tôi thì những vị trí lãnh đạo rạp xiếc cấp cao phải tìm người có tâm, có tầm. Một môi trường của những thiên tài hề, xung quanh bạn là những nhân vật: cha đẻ của tiếng cười, nhà khoa học hề, chúa hề địa phương, bait đồ tể, chúa tể rạp xiết Môi trường làm việc năng động, hài hước",
    "Ai mượn bạn nói mà cái địt mẹ bạn lúc lồn nào cũng 'aI hỎi?'. Là tôi, tôi đã hỏi. Thật là một cực hình khi phải nặng gánh trách nhiệm của một kẻ tội đồ đã đưa ra câu hỏi và giấu mình vào ngôi thứ ba. Trách nhiệm nặng như quả đất, đặt vào đôi bờ vai nhỏ bé của tôi. Nó như đè nát thân tâm tôi, nó rằng xé con người tôi bởi sức nặng khủng khiếp của Kẻ Đã Hỏi. Thật là một cực hình, quả là địa ngục trần gian, đúng là tra tấn man rợn. Nhưng cuối cùng, tôi cũng được giải phóng khỏi chuỗi ngày đau khổ đó. Đúng, là tôi, tôi đã hỏi, có vấn đề gì không?"
]